name: Ubuntu
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu latest GCC",
              os: ubuntu-latest,
              cc: "gcc"
            }
    steps:
      - uses: actions/checkout@v1
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Installing dependencies and running tests
        run: |
          ./ci/run_tests.sh
